---
    AWSTemplateFormatVersion: '2010-09-09'
    Description: 'Setup for EC2 and RDS. This purpose is to enable to connect RDS from local'
    Parameters:
      #rds_parameter
      RDSInstanceIdentifier:
          Type: String
          Default: database-1
          Description: Enter RDS InstanceIdentifier to identify RDS.
      RDSInstanceType:
          Type: String
          Default: db.r5.large
          AllowedValues:
          - db.r5.large
          - db.r5.xlarge
          - db.r5.2xlarge
          - db.r5.4xlarge
          Description: Enter RDS InstanceType
      RDSDBPort:
          Default: '3306'
          Type: Number
          MinValue: '1150'
          MaxValue: '65535'
          Description: Enter TCP/IP port used to connect DB in RDS.
      RDSDBPwd:
          NoEcho: 'true'
          Type: String
          MinLength: '1'
          MaxLength: '41'
          AllowedPattern: "^[a-zA-Z0-9]*$"
          Description: Enter the database admin account password in RDS
    Resources:
      #rds
      RDSSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: SecurityGroup rds-grp
          #EKSのVPC
          VpcId: vpc-xxx
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort:
                Ref: RDSDBPort
              ToPort:
                Ref: RDSDBPort
              #EKSのVPCのcidr
              CidrIp: 192.168.0.0/16
      RDSInstance:
        Type: AWS::RDS::DBInstance
        Properties:
          Engine: mysql
          DBInstanceClass:
            Ref: RDSInstanceType
          AllocatedStorage: '20'
          StorageType: gp2
          DBInstanceIdentifier:
            Ref: RDSInstanceIdentifier
          MasterUsername: admin
          MasterUserPassword:
            Ref: RDSDBPwd
          #rdsのサブネットGを設定しないといけないため、そのためだけの構築工数が必要(rdsSubnetG_for_ec2_rds.yml)
          #ここにはそれでできたRDSSubnetGroupの名前を入れる
          DBSubnetGroupName: "xxx"
          PubliclyAccessible: false
          AvailabilityZone: "ap-northeast-1a"
          VPCSecurityGroups:
            - Ref: RDSSecurityGroup
          CopyTagsToSnapshot: true
          BackupRetentionPeriod: 7
          Tags:
            - Key: Application
              Value: string
        DeletionPolicy: Snapshot
